### ISSUE TITLE
Mappings

### ISSUE THREAD

**Issue by unbalancedparentheses** [tsloughter/erlastic_search#18]
I could not find any way to put a mapping when creating and index, or PUTing a mapping to a index/type after its creation.

Will you add support for this?

**Comment by RobinClowers** [comment]
Looks like this got added in 5a81ba018f4aa8eb2352a80f0b5b93dfcad0236b?

**Comment by unbalancedparentheses** [comment]
@RobinClowers yes, I added it :P.
