### ISSUE TITLE
search/5 using uri search when the body is binary string

### ISSUE THREAD

**Issue by nernsting** [tsloughter/erlastic_search#37]
Hi @tsloughter,
i was wondering why search/5 chooses between uri search and body search based on the type of the query. How is the right way to use this API when we are generating our queries via template system and try to pass the resulting binary string as body?

**Comment by tsloughter** [comment]
Do you mean the fact that if it is a binary it uses `?q=` and if not it assumes it is json? So you want to be able to pass a binary json body instead of json that gets encoded in the search function?

**Comment by nilsernsting** [comment]
Exactly, that's what i was trying to do and i didn't expect the search function to contain such a logic. I would recommend to separate the search by URI and body into two different functions.

**Comment by nilsernsting** [comment]
I made a commit df6f30b825c165ca9a71e615c3fc2198a8b54bc7 to demonstrate how i would separate this logic into two different functions. The problem about this solution is that it wouldn't be backward compatible for the URI search and there aren't any default parameter for `search_query`. If you like I would add those and create a pull request. Do you have any further suggestions?
