### ISSUE TITLE
Tests please

### ISSUE THREAD

**Issue by tsloughter** [tsloughter/erlastic_search#69]
I mostly just merge peoples PRs with minimal review. 

I don't use this library so would be great if someone who does would be interested in submitting a travis or circle config that can run the ct tests (and we need more ct tests, a lot more) against a running ElasticSearch that travis or circle provides.

**Comment by joaohf** [comment]
Hi, I use erlastic_search a lot. Tests is very important.

In your opinion what will do the job better: circle or travis?

**Comment by bryanhuntesl** [comment]
Tests now run on Travis against a Elastic Search container.
